"""add indexes

Revision ID: bac5048f4565
Revises: 3b2a7c9d1f1b
Create Date: 2025-12-25 11:53:27.715327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac5048f4565'
down_revision: Union[str, Sequence[str], None] = '3b2a7c9d1f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activities_tenant_actor_created_desc', 'activities', ['tenant_id', 'actor_principal_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_activities_tenant_created_desc', 'activities', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_activities_tenant_resource_created_desc', 'activities', ['tenant_id', 'resource_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    if is_sqlite:
        op.create_index('ix_outbox_publishable', 'outbox', ['published_at', 'created_at'], unique=False)
    else:
        op.create_index('ix_outbox_publishable', 'outbox', [sa.literal_column('published_at NULLS FIRST'), 'created_at'], unique=False)
    op.create_index('ix_resources_tenant_owner', 'resources', ['tenant_id', 'owner_principal_id'], unique=False)
    op.create_index('ix_resources_tenant_parent', 'resources', ['tenant_id', 'parent_id'], unique=False)
    op.create_index('ix_resources_tenant_type', 'resources', ['tenant_id', 'type'], unique=False)
    op.drop_index(op.f('ix_role_bindings_not_revoked'), table_name='role_bindings')
    if is_sqlite:
        op.create_index(
            'ix_role_bindings_tenant_principal_active',
            'role_bindings',
            ['tenant_id', 'principal_id'],
            unique=False,
            sqlite_where=sa.text('revoked_at IS NULL'),
        )
        op.create_index(
            'ix_role_bindings_tenant_scope_active',
            'role_bindings',
            ['tenant_id', 'scope_resource_id'],
            unique=False,
            sqlite_where=sa.text('revoked_at IS NULL'),
        )
    else:
        op.create_index('ix_role_bindings_tenant_principal_active', 'role_bindings', ['tenant_id', 'principal_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
        op.create_index('ix_role_bindings_tenant_scope_active', 'role_bindings', ['tenant_id', 'scope_resource_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite:
        op.drop_index('ix_role_bindings_tenant_scope_active', table_name='role_bindings')
        op.drop_index('ix_role_bindings_tenant_principal_active', table_name='role_bindings')
    else:
        op.drop_index('ix_role_bindings_tenant_scope_active', table_name='role_bindings', postgresql_where=sa.text('revoked_at IS NULL'))
        op.drop_index('ix_role_bindings_tenant_principal_active', table_name='role_bindings', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_role_bindings_not_revoked'), 'role_bindings', ['tenant_id', 'principal_id'], unique=False)
    op.drop_index('ix_resources_tenant_type', table_name='resources')
    op.drop_index('ix_resources_tenant_parent', table_name='resources')
    op.drop_index('ix_resources_tenant_owner', table_name='resources')
    op.drop_index('ix_outbox_publishable', table_name='outbox')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index('ix_activities_tenant_resource_created_desc', table_name='activities')
    op.drop_index('ix_activities_tenant_created_desc', table_name='activities')
    op.drop_index('ix_activities_tenant_actor_created_desc', table_name='activities')
    # ### end Alembic commands ###
