"""Initial schema

Revision ID: e1add04204b8
Revises:
Create Date: 2025-12-24 19:43:02.488309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1add04204b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_principals_tenant_id"), "principals", ["tenant_id"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("perm_name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "resource_type", "role_name", "perm_name"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("owner_principal_id", sa.Uuid(), nullable=False),
        sa.Column("space_kind", sa.String(length=50), nullable=True),
        sa.Column("subspace_kind", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resources_owner_principal_id"),
        "resources",
        ["owner_principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resources_parent_id"), "resources", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_resources_tenant_id"), "resources", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_resources_type"), "resources", ["type"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_principal_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_principal_id", sa.Uuid(), nullable=True),
        sa.Column("visibility", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("authz_decision", sa.String(length=50), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_created_at"), "activities", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activities_tenant_id"), "activities", ["tenant_id"], unique=False
    )
    op.create_table(
        "resource_edges",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("src_resource_id", sa.Uuid(), nullable=False),
        sa.Column("dst_resource_id", sa.Uuid(), nullable=False),
        sa.Column("edge_type", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dst_resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["src_resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "src_resource_id", "dst_resource_id", "edge_type"
        ),
    )
    op.create_index(
        op.f("ix_resource_edges_dst_resource_id"),
        "resource_edges",
        ["dst_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_edges_src_resource_id"),
        "resource_edges",
        ["src_resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_resource_edges_tenant_dst",
        "resource_edges",
        ["tenant_id", "dst_resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_resource_edges_tenant_src",
        "resource_edges",
        ["tenant_id", "src_resource_id"],
        unique=False,
    )
    op.create_table(
        "resource_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("parents", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_ref", sa.String(length=1024), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resource_versions_created_at"),
        "resource_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_versions_resource_id"),
        "resource_versions",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_resource_versions_tenant_res_created",
        "resource_versions",
        ["tenant_id", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "role_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("scope_resource_id", sa.Uuid(), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("granted_by", sa.Uuid(), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_role_bindings_not_revoked",
        "role_bindings",
        ["tenant_id", "principal_id"],
        unique=False,
        postgresql_where="revoked_at IS NULL",
    )
    op.create_index(
        op.f("ix_role_bindings_principal_id"),
        "role_bindings",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_bindings_scope_resource_id"),
        "role_bindings",
        ["scope_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_bindings_tenant_id"), "role_bindings", ["tenant_id"], unique=False
    )
    op.create_table(
        "resource_refs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("ref_name", sa.String(length=255), nullable=False),
        sa.Column("head_version_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["head_version_id"],
            ["resource_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "resource_id", "ref_name"),
    )
    op.create_index(
        op.f("ix_resource_refs_resource_id"),
        "resource_refs",
        ["resource_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resource_refs_resource_id"), table_name="resource_refs")
    op.drop_table("resource_refs")
    op.drop_index(op.f("ix_role_bindings_tenant_id"), table_name="role_bindings")
    op.drop_index(
        op.f("ix_role_bindings_scope_resource_id"), table_name="role_bindings"
    )
    op.drop_index(op.f("ix_role_bindings_principal_id"), table_name="role_bindings")
    op.drop_index(
        "ix_role_bindings_not_revoked",
        table_name="role_bindings",
        postgresql_where="revoked_at IS NULL",
    )
    op.drop_table("role_bindings")
    op.drop_index(
        "ix_resource_versions_tenant_res_created", table_name="resource_versions"
    )
    op.drop_index(
        op.f("ix_resource_versions_resource_id"), table_name="resource_versions"
    )
    op.drop_index(
        op.f("ix_resource_versions_created_at"), table_name="resource_versions"
    )
    op.drop_table("resource_versions")
    op.drop_index("ix_resource_edges_tenant_src", table_name="resource_edges")
    op.drop_index("ix_resource_edges_tenant_dst", table_name="resource_edges")
    op.drop_index(
        op.f("ix_resource_edges_src_resource_id"), table_name="resource_edges"
    )
    op.drop_index(
        op.f("ix_resource_edges_dst_resource_id"), table_name="resource_edges"
    )
    op.drop_table("resource_edges")
    op.drop_index(op.f("ix_activities_tenant_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_created_at"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_resources_type"), table_name="resources")
    op.drop_index(op.f("ix_resources_tenant_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_parent_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_owner_principal_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_principals_tenant_id"), table_name="principals")
    op.drop_table("principals")
    op.drop_table("outbox")
    op.drop_table("tenants")
    # ### end Alembic commands ###
